-- 코드를 입력하세요
SELECT ID, IFNULL(CNT, 0) PURCHASE_COUNT, IFNULL(TP, 0) TOTAL_PRICE
FROM GAME_USERS AS U
    LEFT JOIN
        (SELECT USER_ID, COUNT(*) CNT, SUM(CHARACTERS.PRICE) TP FROM PURCHASES
            LEFT JOIN CHARACTERS ON PURCHASES.ITEM = CHARACTERS.NAME GROUP BY USER_ID) T
    ON U.ID = T.USER_ID
ORDER BY U.ID;