SELECT P.PRODUCT_ID, P.PRODUCT_NAME, O.AMOUNT * P.PRICE AS TOTAL_SALES
FROM (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
      FROM FOOD_ORDER
      WHERE PRODUCE_DATE BETWEEN DATE "2022-05-01" AND DATE "2022-05-31"
      GROUP BY PRODUCT_ID) O
LEFT JOIN FOOD_PRODUCT P ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC;
