SELECT YEAR, MONTH,
    COUNT(*) AS PURCHASED_USERS, 
    ROUND(COUNT(*) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = "2021"), 1) AS PURCHASED_RATIO
FROM (
    SELECT YEAR(S.SALES_DATE) YEAR, MONTH(S.SALES_DATE) MONTH, COUNT(*) CNT
    FROM ONLINE_SALE S
    LEFT JOIN USER_INFO U ON U.USER_ID = S.USER_ID
    WHERE YEAR(U.JOINED) = "2021"
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE), S.USER_ID
) T
GROUP BY YEAR, MONTH
ORDER BY YEAR ASC, MONTH ASC;
